# Generated by Django 3.2.12 on 2022-05-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cluster',
            field=models.IntegerField(default=0),
        ),
    ]
