# Generated by Django 3.2.12 on 2022-05-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors_path',
            field=models.JSONField(null=True),
        ),
    ]
