# Generated by Django 3.2.12 on 2022-05-19 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_review_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='like_genres', to=settings.AUTH_USER_MODEL),
        ),
    ]
