# Generated by Django 3.2.12 on 2022-05-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_genre_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('known_name', models.CharField(max_length=20)),
                ('movies', models.ManyToManyField(blank=True, related_name='actors', to='movies.Movie')),
            ],
        ),
    ]
