# Generated by Django 3.2.12 on 2022-05-25 15:50

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='crew_backdrop',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='media/crew/크루배경기본.png', null=True, upload_to='thumbnails/crew/backdrop/'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='crew_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='media/crew/크루기본.png', null=True, upload_to='thumbnails/crew/image/'),
        ),
    ]
