# Generated by Django 3.2.12 on 2022-05-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('crews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='movies',
            field=models.ManyToManyField(blank=True, to='movies.Movie'),
        ),
    ]
