# Generated by Django 3.2.12 on 2022-05-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0002_auto_20220526_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='crew_location2',
        ),
    ]
