# Generated by Django 3.2.12 on 2022-05-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0002_auto_20220523_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='crew_image',
        ),
    ]
