# Generated by Django 3.2.12 on 2022-05-23 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0003_remove_crew_crew_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewreview',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crews.crewarticle'),
        ),
    ]
