# Generated by Django 3.2.12 on 2022-05-23 08:26

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0004_alter_crewreview_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='crew_backdrop',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='media/김태리.jpg', null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='crew',
            name='crew_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='media/김태리.jpg', null=True, upload_to='thumbnails/'),
        ),
    ]
