# Generated by Django 3.2.12 on 2022-05-23 09:19

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0005_auto_20220523_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='crew_backdrop',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='media/김태리.jpg', null=True, upload_to='thumbnails/crew/backdrop/'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='crew_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='media/김태리.jpg', null=True, upload_to='thumbnails/crew/image/'),
        ),
    ]
