# Generated by Django 3.2.12 on 2022-05-23 09:19

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='backdrop',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='media/tmp_pre6_uenvE9N.jpg', null=True, upload_to='thumbnails/user/backdrop/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='media/김태리.jpg', null=True, upload_to='thumbnails/user/image/'),
        ),
    ]
