# Generated by Django 3.2.12 on 2022-05-25 15:50

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='backdrop',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='media/user/프로필배경기본.png', null=True, upload_to='thumbnails/user/backdrop/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='media/user/프로필기본.png', null=True, upload_to='thumbnails/user/profile/'),
        ),
    ]
