# Generated by Django 3.2.12 on 2022-05-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220526_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location2',
        ),
    ]
